"""GitHub review delivery — turn a ReviewReport into one GitHub review.

Why one review, not N notifications:
GitHub's review API supports posting all comments as a single review (event
COMMENT). The author gets one email and one mention, not one per comment.
Anything else trains the team to mute the bot.

Why the orphan section in the summary body:
Inline comments must anchor to a line that appears in the diff. Out-of-diff
comments (the model wanted to make a point about a line the PR didn't touch)
get folded into the review's summary body under "General observations". That
preserves the signal without GitHub rejecting the whole review.
"""

from __future__ import annotations

from ..github_client import GitHubClient
from ..models import ReviewComment, ReviewReport

_SEVERITY_ICON = {
    "blocking": "🛑",
    "suggestion": "💡",
    "nit": "💬",
}


def post(gh: GitHubClient, report: ReviewReport) -> str:
    """Post the report as one GitHub review. Returns the new review's HTML URL."""
    body = build_summary_body(report)
    inline = build_inline_comments(report.comments)

    raw_pr = gh.get_raw_pr(report.pr)
    review = raw_pr.create_review(
        body=body,
        event="COMMENT",
        comments=inline,
    )
    return review.html_url


# ---------------------------------------------------------------------------
# Payload builders (pure; testable without hitting GitHub)
# ---------------------------------------------------------------------------


def build_inline_comments(comments: list[ReviewComment]) -> list[dict]:
    """Render each inline comment into GitHub's reviewComments payload shape."""
    return [
        {
            "path": c.file_path,
            "line": c.line,
            "side": "RIGHT",
            "body": _format_inline_body(c),
        }
        for c in comments
    ]


def build_summary_body(report: ReviewReport) -> str:
    """Markdown body for the review itself.

    Layout:
        # Smart Code Reviewer
        <one-paragraph summary>
        <stats line>

        ## General observations
        <orphan comments rendered as markdown>
    """
    parts: list[str] = ["## Smart Code Reviewer"]
    if report.summary.strip():
        parts.append(report.summary.strip())

    stats = (
        f"_Passes: {', '.join(report.passes_run) or 'none'}._  "
        f"_Surfaced **{report.total_posted}** of **{report.total_candidates}** "
        f"candidate(s) after filtering._"
    )
    parts.append(stats)

    if report.orphan_comments:
        parts.append("")
        parts.append("### General observations")
        parts.append(
            "_The comments below could not be anchored to a specific line in this PR's diff. "
            "They reference code that exists in the file but wasn't touched._"
        )
        parts.append("")
        for c in report.orphan_comments:
            parts.append(_format_orphan_block(c))

    parts.append("")
    parts.append("<sub>Generated by smart-code-reviewer.</sub>")
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Comment formatting
# ---------------------------------------------------------------------------


def _format_inline_body(c: ReviewComment) -> str:
    icon = _SEVERITY_ICON.get(c.severity, "")
    parts = [f"{icon} **{c.title}**", "", c.body]
    if c.suggested_fix:
        parts += ["", "```suggestion", c.suggested_fix, "```"]
    parts += [
        "",
        f"<sub>`{c.pass_name}` · {c.severity} · confidence {c.confidence:.2f}</sub>",
    ]
    return "\n".join(parts)


def _format_orphan_block(c: ReviewComment) -> str:
    icon = _SEVERITY_ICON.get(c.severity, "")
    parts = [
        f"#### {icon} `{c.file_path}` — {c.title}",
        f"_{c.severity} · {c.category} · confidence {c.confidence:.2f}_",
        "",
        c.body,
    ]
    if c.suggested_fix:
        parts += ["", "```", c.suggested_fix, "```"]
    return "\n".join(parts)
