/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FilePath = string;
export type Line = number;
export type Snippet = string;
export type CallerSymbol = string | null;
export type IsTest = boolean;
export type FilePath1 = string;
export type SymbolName = string;
export type SymbolKind = "function" | "method" | "class";
/**
 * 1-indexed line in the post-image file
 */
export type StartLine = number;
export type EndLine = number;
export type OldSource = string | null;
export type NewSource = string;
export type Language = "python" | "typescript" | "javascript" | "tsx" | "jsx" | "unknown";
export type Owner = string;
export type Repo = string;
export type Number = number;
export type Title = string;
export type Description = string;
export type Author = string;
export type BaseSha = string;
export type HeadSha = string;
export type Url = string;
export type Callers = CallSite[];
export type SiblingSymbols = string[];
export type RelatedTestFiles = string[];
export type ChangedSymbols = SymbolContext[];
export type RepoConventionsSnippet = string;
export type DiffSummary = string;
export type FullDiff = string;
export type TotalInputTokens = number;
export type TotalOutputTokens = number;
export type TotalCostUsd = number;
export type UserCode = string;
export type VerificationUri = string;
export type DeviceCode = string;
export type ExpiresIn = number;
export type Interval = number;
export type Url1 = string;
export type Owner1 = string;
export type Repo1 = string;
export type Number1 = number;
export type Title1 = string;
export type Author1 = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type State = "open" | "closed";
export type Draft = boolean;
export type Stage = "context" | "analysis" | "filtering";
export type Event = "started" | "progress" | "pass_started" | "pass_completed" | "completed";
export type Detail = string | null;
export type Name = string | null;
export type TokensInput = number | null;
export type TokensOutput = number | null;
export type DurationMs = number | null;
export type Id = string;
export type FilePath2 = string;
export type Line1 = number;
export type Category = "readability" | "structure" | "maintainability" | "correctness";
export type Severity = "blocking" | "suggestion" | "nit";
export type Title2 = string;
export type Body = string;
export type Confidence = number;
export type PassName = string;
export type SuggestedFix = string | null;
export type Comments = ReviewComment[];
export type OrphanComments = ReviewComment[];
export type Summary = string;
export type PassesRun = string[];
export type PassesSkipped = string[];
export type TotalCandidates = number;
export type TotalPosted = number;
export type RunId = string | null;
export type AccessToken = string;
/**
 * `PAT` or `OAuth`
 */
export type TokenType = string;
export type Scope = string | null;
export type UserLogin = string;
export type UserId = number | null;
export type CreatedAt1 = string;

/**
 * Auto-generated from the sidecar's Pydantic models. Consumed by the desktop app's build step (quicktype → TypeScript).
 */
export interface CodeReviewWizardSidecarSchemas {
  [k: string]: unknown;
}
/**
 * A place outside the changed symbol where it is referenced or called.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "CallSite".
 */
export interface CallSite {
  file_path: FilePath;
  line: Line;
  snippet: Snippet;
  caller_symbol?: CallerSymbol;
  is_test?: IsTest;
}
/**
 * A function/method/class touched by the diff.
 *
 * We operate on symbols, not raw line ranges. A line diff answers
 * "what bytes moved." A symbol diff answers "what behavior changed."
 * Reviews are about behavior.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "ChangedSymbol".
 */
export interface ChangedSymbol {
  file_path: FilePath1;
  symbol_name: SymbolName;
  symbol_kind: SymbolKind;
  start_line: StartLine;
  end_line: EndLine;
  old_source?: OldSource;
  new_source: NewSource;
  language: Language;
}
/**
 * Everything one analysis pass needs. The output of Stage 1.
 *
 * `diff_line_anchors` lists the post-image lines that appear in the diff
 * for each file. These are the only lines a ReviewComment can be anchored
 * to — GitHub's review API will reject comments on lines outside the diff.
 * The bundle carries this set explicitly so the prompt can show the model
 * what's valid and so post-LLM validation can route orphans to the summary.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "ContextBundle".
 */
export interface ContextBundle {
  pr: PRMetadata;
  changed_symbols: ChangedSymbols;
  repo_conventions_snippet: RepoConventionsSnippet;
  diff_summary: DiffSummary;
  full_diff?: FullDiff;
  diff_line_anchors?: DiffLineAnchors;
}
/**
 * Stable identity of a PR. Carried unchanged through every stage.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "PRMetadata".
 */
export interface PRMetadata {
  owner: Owner;
  repo: Repo;
  number: Number;
  title: Title;
  description?: Description;
  author: Author;
  base_sha: BaseSha;
  head_sha: HeadSha;
  url: Url;
}
/**
 * A ChangedSymbol enriched with surrounding context.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "SymbolContext".
 */
export interface SymbolContext {
  symbol: ChangedSymbol;
  callers?: Callers;
  sibling_symbols?: SiblingSymbols;
  related_test_files?: RelatedTestFiles;
}
export interface DiffLineAnchors {
  [k: string]: number[];
}
/**
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "CostSummary".
 */
export interface CostSummary {
  total_input_tokens?: TotalInputTokens;
  total_output_tokens?: TotalOutputTokens;
  total_cost_usd?: TotalCostUsd;
  by_pass?: ByPass;
}
export interface ByPass {
  [k: string]: {
    [k: string]: number;
  };
}
/**
 * What we show the user during device-flow login.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "DeviceFlowChallenge".
 */
export interface DeviceFlowChallenge {
  user_code: UserCode;
  verification_uri: VerificationUri;
  device_code: DeviceCode;
  expires_in: ExpiresIn;
  interval: Interval;
}
/**
 * Lightweight PR record for the list/discovery surface.
 *
 * Built from GitHub's search API result, which returns issue-shaped objects.
 * Notably absent: additions, deletions, changed_files — those require a per-PR
 * fetch and we keep listing cheap. The full PRMetadata is what `review` and
 * `inspect` build for a specific PR.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "PRSummary".
 */
export interface PRSummary {
  url: Url1;
  owner: Owner1;
  repo: Repo1;
  number: Number1;
  title: Title1;
  author: Author1;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  state?: State;
  draft?: Draft;
}
/**
 * One progress signal from the streaming pipeline.
 *
 * The streaming generator emits these between every meaningful step so the
 * desktop UI (and any CLI watcher) can render real-time progress instead of
 * staring at a 10-second blank wait.
 *
 * Field meanings by event kind:
 *     started / completed   — stage boundary
 *     progress              — within-stage milestone (detail describes it)
 *     pass_started          — Stage 2 only; `name` is the pass name
 *     pass_completed        — Stage 2 only; tokens_* and duration_ms set
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "PipelineEvent".
 */
export interface PipelineEvent {
  stage: Stage;
  event: Event;
  detail?: Detail;
  name?: Name;
  tokens_input?: TokensInput;
  tokens_output?: TokensOutput;
  duration_ms?: DurationMs;
}
/**
 * One candidate review comment, before filtering and posting.
 *
 * `extra="forbid"` keeps the LLM tool-use contract tight: any drift between
 * the prompt's tool schema and this model is a loud failure, not a silent one.
 *
 * `id` is generated on construction (the LLM doesn't supply it). The desktop
 * app uses this id to address specific comments for approve / dismiss / edit
 * triage before the review is posted.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "ReviewComment".
 */
export interface ReviewComment {
  id?: Id;
  file_path: FilePath2;
  line: Line1;
  category: Category;
  severity: Severity;
  title: Title2;
  body: Body;
  confidence: Confidence;
  pass_name: PassName;
  suggested_fix?: SuggestedFix;
}
/**
 * Filtered, prioritized output of Stage 3 — what Stage 4 delivers.
 *
 * `comments` are inline-anchored to specific diff lines.
 * `orphan_comments` are out-of-diff comments rolled into the summary body;
 * GitHub can't line-anchor them, so they ride along in prose instead of
 * being silently dropped.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "ReviewReport".
 */
export interface ReviewReport {
  pr: PRMetadata;
  comments?: Comments;
  orphan_comments?: OrphanComments;
  summary?: Summary;
  passes_run?: PassesRun;
  passes_skipped?: PassesSkipped;
  total_candidates?: TotalCandidates;
  total_posted?: TotalPosted;
  cost_summary?: CostSummary;
  run_id?: RunId;
}
/**
 * Persistent record of a logged-in identity.
 *
 * This interface was referenced by `CodeReviewWizardSidecarSchemas`'s JSON-Schema
 * via the `definition` "StoredAuth".
 */
export interface StoredAuth {
  access_token: AccessToken;
  token_type?: TokenType;
  scope?: Scope;
  user_login: UserLogin;
  user_id?: UserId;
  created_at?: CreatedAt1;
}
